handling edge case of no prior tags

diff --git a/.github/workflows/bump_release.yml b/.github/workflows/bump_release.yml
--- a/.github/workflows/bump_release.yml
+++ b/.github/workflows/bump_release.yml
@@ -67,6 +67,9 @@ jobs:
         if: ${{ !inputs.skip-version-bump }}
         run: |
           VERSION="${{ steps.get_tag.outputs.last_tag }}"
+          if [ -z "$VERSION" ]; then
+            VERSION="v0.0.0"
+          fi
           VERSION="${VERSION#v}"  # Remove the leading "v"
           IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
           case "${{ steps.analyze.outputs.bump_type }}" in
@@ -91,5 +94,9 @@ jobs:
         id: set_output
         run: |
           TAG=${{ steps.version.outputs.new_tag || steps.get_tag.outputs.last_tag }}
+          if [ -z "$TAG" ]; then
+            echo "Error: TAG is empty. Failing the workflow. If you're skipping version bump, you should have at least one tagged releae pre-existing."
+            exit 1
+          fi
           echo "tag=$TAG"
           echo "tag=$TAG" >> "$GITHUB_OUTPUT"
